# Form implementation generated from reading ui file 'softchord_chord_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(470, 149)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.marker_ef = QtWidgets.QLineEdit(parent=Dialog)
        self.marker_ef.setMinimumSize(QtCore.QSize(30, 0))
        self.marker_ef.setMaximumSize(QtCore.QSize(80, 16777215))
        self.marker_ef.setObjectName("marker_ef")
        self.horizontalLayout.addWidget(self.marker_ef)
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.note_menu = QtWidgets.QComboBox(parent=Dialog)
        self.note_menu.setMinimumSize(QtCore.QSize(90, 0))
        self.note_menu.setObjectName("note_menu")
        self.horizontalLayout.addWidget(self.note_menu)
        self.chord_type_menu = QtWidgets.QComboBox(parent=Dialog)
        self.chord_type_menu.setObjectName("chord_type_menu")
        self.horizontalLayout.addWidget(self.chord_type_menu)
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.bass_menu = QtWidgets.QComboBox(parent=Dialog)
        self.bass_menu.setMinimumSize(QtCore.QSize(90, 0))
        self.bass_menu.setObjectName("bass_menu")
        self.horizontalLayout.addWidget(self.bass_menu)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.in_parentheses_box = QtWidgets.QCheckBox(parent=Dialog)
        self.in_parentheses_box.setObjectName("in_parentheses_box")
        self.verticalLayout.addWidget(self.in_parentheses_box)
        spacerItem1 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.note_menu, self.chord_type_menu)
        Dialog.setTabOrder(self.chord_type_menu, self.bass_menu)
        Dialog.setTabOrder(self.bass_menu, self.in_parentheses_box)
        Dialog.setTabOrder(self.in_parentheses_box, self.marker_ef)
        Dialog.setTabOrder(self.marker_ef, self.buttonBox)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Chord Selector"))
        self.label.setText(_translate("Dialog", "Chord for selected letter:"))
        self.label_2.setText(_translate("Dialog", ":"))
        self.label_3.setText(_translate("Dialog", "/"))
        self.in_parentheses_box.setText(_translate("Dialog", "In parentheses"))
