# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'softchord_main_window.ui'
#
# Created: Tue Jul 03 00:08:24 2012
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1087, 809)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.song_filter_ef = QtGui.QLineEdit(self.layoutWidget)
        self.song_filter_ef.setObjectName("song_filter_ef")
        self.horizontalLayout_7.addWidget(self.song_filter_ef)
        self.clear_filter_button = QtGui.QToolButton(self.layoutWidget)
        self.clear_filter_button.setObjectName("clear_filter_button")
        self.horizontalLayout_7.addWidget(self.clear_filter_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.songs_view = QtGui.QTableView(self.layoutWidget)
        self.songs_view.setMinimumSize(QtCore.QSize(100, 80))
        self.songs_view.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.songs_view.setObjectName("songs_view")
        self.verticalLayout_3.addWidget(self.songs_view)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.new_song_button = QtGui.QPushButton(self.layoutWidget)
        self.new_song_button.setObjectName("new_song_button")
        self.horizontalLayout_2.addWidget(self.new_song_button)
        self.delete_song_button = QtGui.QPushButton(self.layoutWidget)
        self.delete_song_button.setObjectName("delete_song_button")
        self.horizontalLayout_2.addWidget(self.delete_song_button)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.song_num_ef = QtGui.QLineEdit(self.layoutWidget1)
        self.song_num_ef.setMaximumSize(QtCore.QSize(50, 16777215))
        self.song_num_ef.setObjectName("song_num_ef")
        self.horizontalLayout.addWidget(self.song_num_ef)
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.song_title_ef = QtGui.QLineEdit(self.layoutWidget1)
        self.song_title_ef.setObjectName("song_title_ef")
        self.horizontalLayout.addWidget(self.song_title_ef)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.song_key_menu = QtGui.QComboBox(self.layoutWidget1)
        self.song_key_menu.setMinimumSize(QtCore.QSize(100, 0))
        self.song_key_menu.setMaximumSize(QtCore.QSize(100, 16777215))
        self.song_key_menu.setObjectName("song_key_menu")
        self.horizontalLayout_4.addWidget(self.song_key_menu)
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.song_alt_key_menu = QtGui.QComboBox(self.layoutWidget1)
        self.song_alt_key_menu.setMinimumSize(QtCore.QSize(50, 0))
        self.song_alt_key_menu.setMaximumSize(QtCore.QSize(60, 16777215))
        self.song_alt_key_menu.setObjectName("song_alt_key_menu")
        self.horizontalLayout_4.addWidget(self.song_alt_key_menu)
        self.label_11 = QtGui.QLabel(self.layoutWidget1)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.song_subtitle_ef = QtGui.QLineEdit(self.layoutWidget1)
        self.song_subtitle_ef.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.song_subtitle_ef.setObjectName("song_subtitle_ef")
        self.horizontalLayout_4.addWidget(self.song_subtitle_ef)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.chord_editor_button = QtGui.QToolButton(self.layoutWidget1)
        self.chord_editor_button.setObjectName("chord_editor_button")
        self.horizontalLayout_6.addWidget(self.chord_editor_button)
        self.lyric_editor_button = QtGui.QToolButton(self.layoutWidget1)
        self.lyric_editor_button.setObjectName("lyric_editor_button")
        self.horizontalLayout_6.addWidget(self.lyric_editor_button)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.label_12 = QtGui.QLabel(self.layoutWidget1)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.transpose_down_button = QtGui.QPushButton(self.layoutWidget1)
        self.transpose_down_button.setObjectName("transpose_down_button")
        self.horizontalLayout_6.addWidget(self.transpose_down_button)
        self.transpose_up_button = QtGui.QPushButton(self.layoutWidget1)
        self.transpose_up_button.setObjectName("transpose_up_button")
        self.horizontalLayout_6.addWidget(self.transpose_up_button)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.lyric_editor_layout = QtGui.QVBoxLayout()
        self.lyric_editor_layout.setObjectName("lyric_editor_layout")
        self.chord_scroll_area = QtGui.QScrollArea(self.layoutWidget1)
        self.chord_scroll_area.setMinimumSize(QtCore.QSize(100, 100))
        self.chord_scroll_area.setFrameShape(QtGui.QFrame.StyledPanel)
        self.chord_scroll_area.setFrameShadow(QtGui.QFrame.Sunken)
        self.chord_scroll_area.setWidgetResizable(True)
        self.chord_scroll_area.setObjectName("chord_scroll_area")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.chord_scroll_area)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 651, 542))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.chord_scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.lyric_editor_layout.addWidget(self.chord_scroll_area)
        self.verticalLayout.addLayout(self.lyric_editor_layout)
        self.chords_editor_label = QtGui.QLabel(self.layoutWidget1)
        self.chords_editor_label.setWordWrap(True)
        self.chords_editor_label.setObjectName("chords_editor_label")
        self.verticalLayout.addWidget(self.chords_editor_label)
        self.lyrics_editor_label = QtGui.QLabel(self.layoutWidget1)
        self.lyrics_editor_label.setWordWrap(True)
        self.lyrics_editor_label.setObjectName("lyrics_editor_label")
        self.verticalLayout.addWidget(self.lyrics_editor_label)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.zoom_out_button = QtGui.QToolButton(self.layoutWidget1)
        self.zoom_out_button.setObjectName("zoom_out_button")
        self.horizontalLayout_3.addWidget(self.zoom_out_button)
        self.zoom_slider = QtGui.QSlider(self.layoutWidget1)
        self.zoom_slider.setOrientation(QtCore.Qt.Horizontal)
        self.zoom_slider.setObjectName("zoom_slider")
        self.horizontalLayout_3.addWidget(self.zoom_slider)
        self.zoom_in_button = QtGui.QToolButton(self.layoutWidget1)
        self.zoom_in_button.setObjectName("zoom_in_button")
        self.horizontalLayout_3.addWidget(self.zoom_in_button)
        self.zoom_label = QtGui.QLabel(self.layoutWidget1)
        self.zoom_label.setObjectName("zoom_label")
        self.horizontalLayout_3.addWidget(self.zoom_label)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1087, 22))
        self.menubar.setObjectName("menubar")
        self.menuSong = QtGui.QMenu(self.menubar)
        self.menuSong.setObjectName("menuSong")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNewSong = QtGui.QAction(MainWindow)
        self.actionNewSong.setObjectName("actionNewSong")
        self.actionDeleteSong = QtGui.QAction(MainWindow)
        self.actionDeleteSong.setObjectName("actionDeleteSong")
        self.actionExportText = QtGui.QAction(MainWindow)
        self.actionExportText.setObjectName("actionExportText")
        self.actionPrint = QtGui.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionLyricsFont = QtGui.QAction(MainWindow)
        self.actionLyricsFont.setObjectName("actionLyricsFont")
        self.actionChordsFont = QtGui.QAction(MainWindow)
        self.actionChordsFont.setObjectName("actionChordsFont")
        self.actionImportText = QtGui.QAction(MainWindow)
        self.actionImportText.setObjectName("actionImportText")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionCloseSongbook = QtGui.QAction(MainWindow)
        self.actionCloseSongbook.setObjectName("actionCloseSongbook")
        self.actionOpenSongbook = QtGui.QAction(MainWindow)
        self.actionOpenSongbook.setObjectName("actionOpenSongbook")
        self.actionNewSongbook = QtGui.QAction(MainWindow)
        self.actionNewSongbook.setObjectName("actionNewSongbook")
        self.actionUndo = QtGui.QAction(MainWindow)
        self.actionUndo.setShortcutContext(QtCore.Qt.WidgetShortcut)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtGui.QAction(MainWindow)
        self.actionRedo.setShortcutContext(QtCore.Qt.WidgetShortcut)
        self.actionRedo.setObjectName("actionRedo")
        self.actionSaveSongbook = QtGui.QAction(MainWindow)
        self.actionSaveSongbook.setObjectName("actionSaveSongbook")
        self.actionExportMultiplePdfs = QtGui.QAction(MainWindow)
        self.actionExportMultiplePdfs.setObjectName("actionExportMultiplePdfs")
        self.actionSelectAll = QtGui.QAction(MainWindow)
        self.actionSelectAll.setShortcutContext(QtCore.Qt.WidgetShortcut)
        self.actionSelectAll.setObjectName("actionSelectAll")
        self.actionImportChordPro = QtGui.QAction(MainWindow)
        self.actionImportChordPro.setObjectName("actionImportChordPro")
        self.actionExportChordPro = QtGui.QAction(MainWindow)
        self.actionExportChordPro.setObjectName("actionExportChordPro")
        self.actionSetID = QtGui.QAction(MainWindow)
        self.actionSetID.setObjectName("actionSetID")
        self.actionCopySongText = QtGui.QAction(MainWindow)
        self.actionCopySongText.setObjectName("actionCopySongText")
        self.actionPasteAsNewSong = QtGui.QAction(MainWindow)
        self.actionPasteAsNewSong.setObjectName("actionPasteAsNewSong")
        self.actionDeleteSongs = QtGui.QAction(MainWindow)
        self.actionDeleteSongs.setObjectName("actionDeleteSongs")
        self.actionExportSongPDF = QtGui.QAction(MainWindow)
        self.actionExportSongPDF.setObjectName("actionExportSongPDF")
        self.actionExportSinglePdf = QtGui.QAction(MainWindow)
        self.actionExportSinglePdf.setObjectName("actionExportSinglePdf")
        self.actionImportClipboard = QtGui.QAction(MainWindow)
        self.actionImportClipboard.setObjectName("actionImportClipboard")
        self.actionExportClipboard = QtGui.QAction(MainWindow)
        self.actionExportClipboard.setObjectName("actionExportClipboard")
        self.actionZoomIn = QtGui.QAction(MainWindow)
        self.actionZoomIn.setObjectName("actionZoomIn")
        self.actionZoomOut = QtGui.QAction(MainWindow)
        self.actionZoomOut.setObjectName("actionZoomOut")
        self.actionZoomActual = QtGui.QAction(MainWindow)
        self.actionZoomActual.setObjectName("actionZoomActual")
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionCut = QtGui.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtGui.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionExportSongToPdf = QtGui.QAction(MainWindow)
        self.actionExportSongToPdf.setObjectName("actionExportSongToPdf")
        self.actionRemoveTrailingSpaces = QtGui.QAction(MainWindow)
        self.actionRemoveTrailingSpaces.setObjectName("actionRemoveTrailingSpaces")
        self.actionAppendSongbook = QtGui.QAction(MainWindow)
        self.actionAppendSongbook.setObjectName("actionAppendSongbook")
        self.actionRenumberSongs = QtGui.QAction(MainWindow)
        self.actionRenumberSongs.setObjectName("actionRenumberSongs")
        self.actionChordEditorMode = QtGui.QAction(MainWindow)
        self.actionChordEditorMode.setObjectName("actionChordEditorMode")
        self.actionLyricEditorMode = QtGui.QAction(MainWindow)
        self.actionLyricEditorMode.setObjectName("actionLyricEditorMode")
        self.menuSong.addAction(self.actionSetID)
        self.menuSong.addAction(self.actionDeleteSong)
        self.menuSong.addSeparator()
        self.menuSong.addAction(self.actionExportText)
        self.menuSong.addAction(self.actionExportChordPro)
        self.menuSong.addAction(self.actionExportClipboard)
        self.menuSong.addAction(self.actionExportSongToPdf)
        self.menuFile.addAction(self.actionNewSongbook)
        self.menuFile.addAction(self.actionOpenSongbook)
        self.menuFile.addAction(self.actionCloseSongbook)
        self.menuFile.addAction(self.actionSaveSongbook)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImportClipboard)
        self.menuFile.addAction(self.actionImportChordPro)
        self.menuFile.addAction(self.actionImportText)
        self.menuFile.addAction(self.actionAppendSongbook)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExportSinglePdf)
        self.menuFile.addAction(self.actionExportMultiplePdfs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuFile.addSeparator()
        self.menuSettings.addAction(self.actionLyricsFont)
        self.menuSettings.addAction(self.actionChordsFont)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionZoomIn)
        self.menuSettings.addAction(self.actionZoomOut)
        self.menuSettings.addAction(self.actionZoomActual)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionCopySongText)
        self.menuEdit.addAction(self.actionPasteAsNewSong)
        self.menuEdit.addAction(self.actionSelectAll)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionNewSong)
        self.menuEdit.addAction(self.actionDeleteSongs)
        self.menuEdit.addAction(self.actionRemoveTrailingSpaces)
        self.menuEdit.addAction(self.actionRenumberSongs)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionChordEditorMode)
        self.menuEdit.addAction(self.actionLyricEditorMode)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSong.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "softChord Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Songs in the current songbook:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Filter:", None, QtGui.QApplication.UnicodeUTF8))
        self.clear_filter_button.setText(QtGui.QApplication.translate("MainWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.new_song_button.setText(QtGui.QApplication.translate("MainWindow", "New Song", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_song_button.setText(QtGui.QApplication.translate("MainWindow", "Delete selected", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Current song:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Number:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Title:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Key:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Alternative key:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Notes:", None, QtGui.QApplication.UnicodeUTF8))
        self.chord_editor_button.setToolTip(QtGui.QApplication.translate("MainWindow", "Enter chord editing mode (⌘K)", None, QtGui.QApplication.UnicodeUTF8))
        self.chord_editor_button.setText(QtGui.QApplication.translate("MainWindow", "Chord Editor Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.lyric_editor_button.setToolTip(QtGui.QApplication.translate("MainWindow", "Enter lyric editing mode (⌘L)", None, QtGui.QApplication.UnicodeUTF8))
        self.lyric_editor_button.setText(QtGui.QApplication.translate("MainWindow", "Lyric Editor Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Transpose:", None, QtGui.QApplication.UnicodeUTF8))
        self.transpose_down_button.setText(QtGui.QApplication.translate("MainWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.transpose_up_button.setText(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.chords_editor_label.setText(QtGui.QApplication.translate("MainWindow", "Chord Editor - Double-click on a lyric letter to add or modify a chord; drag a chord to move it; select and press \"Delete\" to delete; select and press a key to add simple chords.", None, QtGui.QApplication.UnicodeUTF8))
        self.lyrics_editor_label.setText(QtGui.QApplication.translate("MainWindow", "Lyric Editor - Paste and modify song lyrics (text) here.", None, QtGui.QApplication.UnicodeUTF8))
        self.zoom_out_button.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.zoom_in_button.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.zoom_label.setText(QtGui.QApplication.translate("MainWindow", "Zoom: 100%", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSong.setTitle(QtGui.QApplication.translate("MainWindow", "Song", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewSong.setText(QtGui.QApplication.translate("MainWindow", "New Song", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewSong.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeleteSong.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportText.setText(QtGui.QApplication.translate("MainWindow", "Export To TEXT...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setText(QtGui.QApplication.translate("MainWindow", "Print...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLyricsFont.setText(QtGui.QApplication.translate("MainWindow", "Lyrics Font...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChordsFont.setText(QtGui.QApplication.translate("MainWindow", "Chords Font...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImportText.setText(QtGui.QApplication.translate("MainWindow", "Import From TEXT...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCloseSongbook.setText(QtGui.QApplication.translate("MainWindow", "Close Songbook", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCloseSongbook.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenSongbook.setText(QtGui.QApplication.translate("MainWindow", "Open Songbook...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenSongbook.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewSongbook.setText(QtGui.QApplication.translate("MainWindow", "New Songbook...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setText(QtGui.QApplication.translate("MainWindow", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setText(QtGui.QApplication.translate("MainWindow", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveSongbook.setText(QtGui.QApplication.translate("MainWindow", "Save Songbook As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportMultiplePdfs.setText(QtGui.QApplication.translate("MainWindow", "Export to Multiple PDFs...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectAll.setText(QtGui.QApplication.translate("MainWindow", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectAll.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImportChordPro.setText(QtGui.QApplication.translate("MainWindow", "Import From ChordPro...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportChordPro.setText(QtGui.QApplication.translate("MainWindow", "Export To ChordPro...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSetID.setText(QtGui.QApplication.translate("MainWindow", "Set Database ID...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopySongText.setText(QtGui.QApplication.translate("MainWindow", "Copy Song Text", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPasteAsNewSong.setText(QtGui.QApplication.translate("MainWindow", "Paste As New Song", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeleteSongs.setText(QtGui.QApplication.translate("MainWindow", "Delete Selected songs", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportSongPDF.setText(QtGui.QApplication.translate("MainWindow", "Export to PDF...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportSinglePdf.setText(QtGui.QApplication.translate("MainWindow", "Export to PDF...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImportClipboard.setText(QtGui.QApplication.translate("MainWindow", "Import From Clipboard...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportClipboard.setText(QtGui.QApplication.translate("MainWindow", "Export To Clipboard", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomIn.setText(QtGui.QApplication.translate("MainWindow", "Zoom In", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomIn.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+=", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomOut.setText(QtGui.QApplication.translate("MainWindow", "Zoom Out", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomOut.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+-", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZoomActual.setText(QtGui.QApplication.translate("MainWindow", "Actual Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("MainWindow", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("MainWindow", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("MainWindow", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportSongToPdf.setText(QtGui.QApplication.translate("MainWindow", "Export To PDF...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemoveTrailingSpaces.setText(QtGui.QApplication.translate("MainWindow", "Remove Trailing Spaces", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemoveTrailingSpaces.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove trailing spaces from every line in the selected song(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAppendSongbook.setText(QtGui.QApplication.translate("MainWindow", "Append Another Songbook...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRenumberSongs.setText(QtGui.QApplication.translate("MainWindow", "Renumber all songs...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChordEditorMode.setText(QtGui.QApplication.translate("MainWindow", "Chord Editor Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChordEditorMode.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+K", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLyricEditorMode.setText(QtGui.QApplication.translate("MainWindow", "Lyric Editor Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLyricEditorMode.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))

